### PR TITLE
Adding an Alert and logout event

### PR DESCRIPTION
**Pull request by aahenry51**

### CODE REVIEW

**Comment by aahenry51** [comment]
It successfully logins out however there is an alert event for every screen. There has to be a way to pass this component but its not working for some reason.

**Comment by aahenry51** [comment]
image
prompt to logout

**Comment by aahenry51** [comment]
image
Logout

**Comment by aahenry51** [comment]
I successfully logs out using the 'const {signOut} = useContext(AppContext);' hook

**Review by Nap1400 — APPROVED** [review]

**Comment by Dulaya** [comment]
Don't need. No Alert. Close it. Not use alert, just logout.

**Comment by Dulaya** [comment]
Don't need. No Alert. Close it. Not use alert, just logout.

**Pull request closed without merging**
