### PR TITLE
Disable and Enable Button on Detail Screen/ Alphi

### PR DESCRIPTION
**Pull request by aahenry51**

### CODE REVIEW

**Review by raynesmike — APPROVED** [review]
I approve this, you can merge it once you have enough approval

**Comment by aahenry51** [comment]
image
Disabled with no text

**Comment by aahenry51** [comment]
image
Enabled with text

**Comment by aahenry51** [comment]
Hang on, on figma the disabled color is a bit darker

**Comment by aahenry51** [comment]
image
Conflicts fixed

**Review by Nap1400 — APPROVED** [review]
Pretty sure this should work.

**Review by carizzuti — APPROVED** [review]
Looks like it will work

**Pull request merged**
