### PR TITLE
Header: use common styles

### PR DESCRIPTION
**Pull request by Dulaya**
- Remove complex code
- Use common theme
- Build Header in a separate file

### CODE REVIEW

**Comment by Dulaya** [comment]
image

**Review by mshago — APPROVED** [review]
It looks great to me.

**Review by raynesmike — APPROVED** [review]
The addition for the Header is good

**Comment by aahenry51** [comment]
Good, nice work on the button

**Review by aahenry51 — COMMENTED** [review]
Good work

**Review by aahenry51 — APPROVED** [review]

**Pull request merged**
